In [2]:
import polars as pl

## Load & Parse: /data/csv/tweet_emotion_dataset.csv

Source: https://www.kaggle.com/datasets/pashupatigupta/emotion-detection-from-text

In [144]:
tweet_emotion = (
    pl.read_csv("../data/csv/tweet_emotion_dataset.csv")
    .rename({"sentiment": "emotion"})
    .select(["content", "emotion"])
    .with_row_index("tweet_id")
    .select(["tweet_id", "content", "emotion"])
)

tweet_emotion

shape: (40_000, 3)
┌──────────┬─────────────────────────────────┬────────────┐
│ tweet_id ┆ content                         ┆ emotion    │
│ ---      ┆ ---                             ┆ ---        │
│ u32      ┆ str                             ┆ str        │
╞══════════╪═════════════════════════════════╪════════════╡
│ 0        ┆ @tiffanylue i know  i was list… ┆ empty      │
│ 1        ┆ Layin n bed with a headache  u… ┆ sadness    │
│ 2        ┆ Funeral ceremony...gloomy frid… ┆ sadness    │
│ 3        ┆ wants to hang out with friends… ┆ enthusiasm │
│ 4        ┆ @dannycastillo We want to trad… ┆ neutral    │
│ …        ┆ …                               ┆ …          │
│ 39995    ┆ @JohnLloydTaylor                ┆ neutral    │
│ 39996    ┆ Happy Mothers Day  All my love  ┆ love       │
│ 39997    ┆ Happy Mother's Day to all the … ┆ love       │
│ 39998    ┆ @niariley WASSUP BEAUTIFUL!!! … ┆ happiness  │
│ 39999    ┆ @mopedronin bullet train from … ┆ love       │
└──────────┴─────────────────────────────────┴────────────┘

## Load & Parse: /data/csv/emotion_sentiment_dataset.csv

Source: https://www.kaggle.com/datasets/simaanjali/emotion-analysis-based-on-text/data

In [145]:
text_emotion = (
    pl.read_csv("../data/csv/emotion_sentiment_dataset.csv")
    .rename({"text" : "content", "Emotion" : "emotion"})
    .select(["content", "emotion"])
    .with_row_index("text_id")
    .select(["text_id", "content", "emotion"])
)

text_emotion

shape: (839_555, 3)
┌─────────┬─────────────────────────────────┬─────────┐
│ text_id ┆ content                         ┆ emotion │
│ ---     ┆ ---                             ┆ ---     │
│ u32     ┆ str                             ┆ str     │
╞═════════╪═════════════════════════════════╪═════════╡
│ 0       ┆ i seriously hate one subject t… ┆ hate    │
│ 1       ┆ im so full of life i feel appa… ┆ neutral │
│ 2       ┆ i sit here to write i start to… ┆ neutral │
│ 3       ┆ ive been really angry with r a… ┆ anger   │
│ 4       ┆ i feel suspicious if there is … ┆ neutral │
│ …       ┆ …                               ┆ …       │
│ 839550  ┆ i feel like telling these horn… ┆ neutral │
│ 839551  ┆ i began to realize that when i… ┆ neutral │
│ 839552  ┆ i feel very curious be why pre… ┆ neutral │
│ 839553  ┆ i feel that becuase of the tyr… ┆ neutral │
│ 839554  ┆ i think that after i had spent… ┆ neutral │
└─────────┴─────────────────────────────────┴─────────┘

Test if both emotion categories align!

In [147]:
tweet_emotion_categories = tweet_emotion.select("emotion").unique("emotion").sort("emotion")
emotion_sentiment_categories = text_emotion.select("emotion").unique("emotion").sort("emotion")

tweet_emotion_categories.equals(emotion_sentiment_categories)

True

# Export Parquets

In [148]:
tweet_emotion.write_parquet("../data/tweet_emotion.parquet")

text_emotion.write_parquet("../data/text_emotion.parquet")